{{- if .Values.kueue.enabled }}
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: {{ .Values.kueue.clusterQueue.name }}
spec:
  namespaceSelector: {}
  resourceGroups:
  - coveredResources: ["cpu", "memory", "pods"]
    flavors:
    - name: {{ .Values.kueue.resourceFlavor.name }}
      resources:
      {{- range .Values.kueue.clusterQueue.resources }}
      - name: {{ .name | quote }}
        nominalQuota: {{ .nominalQuota }}
      {{- end }}
  queueingStrategy: {{ .Values.kueue.clusterQueue.queueingStrategy }}
{{- end }}
